name: Lint

on:
  pull_request:
    paths:
      - "gigantic_minecraft/**"

jobs:
  lint-protos:
    name: Lint protobuf definitions and push to Buf Schema Registry
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: bufbuild/buf-setup-action@v1

      # Lint Protobuf sources
      - uses: bufbuild/buf-lint-action@v1

      # Check breaking changes
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: "https://github.com/GiganticMinecraft/seichi-game-data-protocol.git#branch=master"
